# Generated by Django 5.1.2 on 2024-10-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=5)),
            ],
        ),
    ]
