# Generated by Django 5.1.2 on 2024-11-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='qrdata',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
